name: Compile

on: push

permissions:
  contents: read
  packages: read

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'

      - name: Build application artifact
        working-directory: server
        run: ./mvnw -DskipTests --batch-mode clean compile;
